"""
B 站登录态相关工具：把 .env 里配的 SESSDATA 包装成 yt-dlp 能吃的 Netscape cookies.txt，
以及给字幕直链请求拼 Cookie / Referer。

需登录的字幕（AI 生成、AI 翻译、部分 UP 上传）拿不到时，B 站 /x/player/v2 会返回
need_login_subtitle: true 且 subtitles 列表为空。本模块只对 B 站 URL 生效，
其他平台（YouTube、抖音等）完全走原路径，避免回归。
"""

from __future__ import annotations

import json
import logging
import os
import tempfile
from dataclasses import dataclass
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse
from urllib.request import Request, urlopen

from .settings import BILIBILI_BILI_JCT, BILIBILI_BUVID3, BILIBILI_SESSDATA


logger = logging.getLogger(__name__)


_BILIBILI_HOST_SUFFIXES = (
    "bilibili.com",
    "b23.tv",
    "hdslb.com",  # 字幕 / 封面 CDN
    "biliapi.net",
)

BILIBILI_REFERER = "https://www.bilibili.com"
BILIBILI_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)


@dataclass(frozen=True)
class BilibiliCookieBundle:
    sessdata: str
    bili_jct: str
    buvid3: str

    @property
    def has_login(self) -> bool:
        return bool(self.sessdata)

    def cookie_header(self) -> str:
        parts: list[str] = []
        if self.sessdata:
            parts.append(f"SESSDATA={self.sessdata}")
        if self.bili_jct:
            parts.append(f"bili_jct={self.bili_jct}")
        if self.buvid3:
            parts.append(f"buvid3={self.buvid3}")
        return "; ".join(parts)


def _is_bilibili_host(host: str) -> bool:
    host = host.lower().strip(".")
    return any(host == suffix or host.endswith("." + suffix) for suffix in _BILIBILI_HOST_SUFFIXES)


def is_bilibili_url(url: str) -> bool:
    try:
        host = (urlparse(url).hostname or "").lower()
    except (TypeError, ValueError):
        return False
    return _is_bilibili_host(host)


def get_cookie_bundle() -> BilibiliCookieBundle:
    return BilibiliCookieBundle(
        sessdata=BILIBILI_SESSDATA,
        bili_jct=BILIBILI_BILI_JCT,
        buvid3=BILIBILI_BUVID3,
    )


def write_netscape_cookie_file(bundle: BilibiliCookieBundle) -> str | None:
    """把 Cookie 写成 yt-dlp 接受的 Netscape 格式临时文件，返回文件路径。

    没有任何 Cookie 时返回 None；调用方在用完后应当 unlink 该文件。
    """
    if not (bundle.sessdata or bundle.bili_jct or bundle.buvid3):
        return None

    lines = ["# Netscape HTTP Cookie File", "# Auto-generated by free-video-download"]

    def _row(name: str, value: str) -> str:
        # domain / flag / path / secure / expiry / name / value (TAB 分隔)
        # 这里用一个远期过期时间，避免 yt-dlp 解析为已过期。
        return "\t".join([
            ".bilibili.com",
            "TRUE",
            "/",
            "TRUE",
            "2147483647",
            name,
            value,
        ])

    if bundle.sessdata:
        lines.append(_row("SESSDATA", bundle.sessdata))
    if bundle.bili_jct:
        lines.append(_row("bili_jct", bundle.bili_jct))
    if bundle.buvid3:
        lines.append(_row("buvid3", bundle.buvid3))
    lines.append("")  # 末尾空行避免某些解析器报错

    fd, path = tempfile.mkstemp(prefix="fvd_bili_", suffix=".cookies.txt", text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fp:
            fp.write("\n".join(lines))
    except Exception:
        try:
            os.unlink(path)
        except OSError:
            pass
        raise
    return path


def safe_unlink(path: str | None) -> None:
    if not path:
        return
    try:
        os.unlink(path)
    except OSError:
        pass


@dataclass(frozen=True)
class BilibiliLoginStatus:
    """运营方共享小号在 B 站当前的登录态。"""

    is_login: bool
    uname: str | None  # 登录用户名（用于运营自检显示）
    mid: int | None  # 用户 mid，用于运营自检
    code: int  # B 站返回的 code，0=正常、-101=未登录
    message: str  # B 站返回的原文 message
    has_cookie: bool  # 站点 .env 里是否配置了 SESSDATA


def check_cookie_login(bundle: BilibiliCookieBundle | None = None) -> BilibiliLoginStatus:
    """直接调 B 站 /x/web-interface/nav 验证当前 Cookie 是否仍被识别为登录态。

    关键场景：SESSDATA 结构上没到期但被 B 站主动吊销时（小号被风控等），
    此处会拿到 code=-101 / isLogin=False，让上游能给出 "Cookie 失效" 而不是
    "视频没字幕" 的误导文案。
    """
    bundle = bundle or get_cookie_bundle()
    if not bundle.has_login:
        return BilibiliLoginStatus(
            is_login=False,
            uname=None,
            mid=None,
            code=-1,
            message="未配置 BILIBILI_SESSDATA",
            has_cookie=False,
        )

    headers = {
        "User-Agent": BILIBILI_USER_AGENT,
        "Referer": BILIBILI_REFERER,
        "Accept": "*/*",
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
        "Cookie": bundle.cookie_header(),
    }
    request = Request("https://api.bilibili.com/x/web-interface/nav", headers=headers)
    try:
        with urlopen(request, timeout=10) as response:
            payload = json.loads(response.read().decode("utf-8", errors="replace"))
    except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as exc:
        logger.warning("[bilibili] cookie nav check failed: %s", exc)
        # 网络错误：保守地返回未知，按 has_cookie=True 但 is_login=False 处理
        return BilibiliLoginStatus(
            is_login=False,
            uname=None,
            mid=None,
            code=-2,
            message=f"无法访问 B 站校验登录态：{exc}",
            has_cookie=True,
        )

    code = int(payload.get("code") or 0)
    message = str(payload.get("message") or "")
    data = payload.get("data") or {}
    return BilibiliLoginStatus(
        is_login=bool(data.get("isLogin")),
        uname=data.get("uname") or None,
        mid=int(data.get("mid")) if data.get("mid") else None,
        code=code,
        message=message,
        has_cookie=True,
    )


def build_subtitle_request_headers(url: str, bundle: BilibiliCookieBundle | None = None) -> dict[str, str]:
    """字幕 / API 直链请求时的 HTTP 头。

    - 对 B 站域名拼上 Referer + UA + Cookie；
    - 其他域名只回默认 UA，避免误带 Cookie 给第三方。
    """
    if not is_bilibili_url(url):
        return {"User-Agent": "Mozilla/5.0 (compatible; FreeVideoDownload/1.0)", "Accept": "*/*"}

    bundle = bundle or get_cookie_bundle()
    headers = {
        "User-Agent": BILIBILI_USER_AGENT,
        "Accept": "*/*",
        "Referer": BILIBILI_REFERER,
        "Origin": BILIBILI_REFERER,
    }
    cookie = bundle.cookie_header()
    if cookie:
        headers["Cookie"] = cookie
    return headers
