"""
B 站登录态相关工具：把 .env 里配的 SESSDATA 包装成 yt-dlp 能吃的 Netscape cookies.txt，
以及给字幕直链请求拼 Cookie / Referer。

需登录的字幕（AI 生成、AI 翻译、部分 UP 上传）拿不到时，B 站 /x/player/v2 会返回
need_login_subtitle: true 且 subtitles 列表为空。本模块只对 B 站 URL 生效，
其他平台（YouTube、抖音等）完全走原路径，避免回归。
"""

from __future__ import annotations

import os
import tempfile
from dataclasses import dataclass
from urllib.parse import urlparse

from .settings import BILIBILI_BILI_JCT, BILIBILI_BUVID3, BILIBILI_SESSDATA


_BILIBILI_HOST_SUFFIXES = (
    "bilibili.com",
    "b23.tv",
    "hdslb.com",  # 字幕 / 封面 CDN
    "biliapi.net",
)

BILIBILI_REFERER = "https://www.bilibili.com"
BILIBILI_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)


@dataclass(frozen=True)
class BilibiliCookieBundle:
    sessdata: str
    bili_jct: str
    buvid3: str

    @property
    def has_login(self) -> bool:
        return bool(self.sessdata)

    def cookie_header(self) -> str:
        parts: list[str] = []
        if self.sessdata:
            parts.append(f"SESSDATA={self.sessdata}")
        if self.bili_jct:
            parts.append(f"bili_jct={self.bili_jct}")
        if self.buvid3:
            parts.append(f"buvid3={self.buvid3}")
        return "; ".join(parts)


def _is_bilibili_host(host: str) -> bool:
    host = host.lower().strip(".")
    return any(host == suffix or host.endswith("." + suffix) for suffix in _BILIBILI_HOST_SUFFIXES)


def is_bilibili_url(url: str) -> bool:
    try:
        host = (urlparse(url).hostname or "").lower()
    except (TypeError, ValueError):
        return False
    return _is_bilibili_host(host)


def get_cookie_bundle() -> BilibiliCookieBundle:
    return BilibiliCookieBundle(
        sessdata=BILIBILI_SESSDATA,
        bili_jct=BILIBILI_BILI_JCT,
        buvid3=BILIBILI_BUVID3,
    )


def write_netscape_cookie_file(bundle: BilibiliCookieBundle) -> str | None:
    """把 Cookie 写成 yt-dlp 接受的 Netscape 格式临时文件，返回文件路径。

    没有任何 Cookie 时返回 None；调用方在用完后应当 unlink 该文件。
    """
    if not (bundle.sessdata or bundle.bili_jct or bundle.buvid3):
        return None

    lines = ["# Netscape HTTP Cookie File", "# Auto-generated by free-video-download"]

    def _row(name: str, value: str) -> str:
        # domain / flag / path / secure / expiry / name / value (TAB 分隔)
        # 这里用一个远期过期时间，避免 yt-dlp 解析为已过期。
        return "\t".join([
            ".bilibili.com",
            "TRUE",
            "/",
            "TRUE",
            "2147483647",
            name,
            value,
        ])

    if bundle.sessdata:
        lines.append(_row("SESSDATA", bundle.sessdata))
    if bundle.bili_jct:
        lines.append(_row("bili_jct", bundle.bili_jct))
    if bundle.buvid3:
        lines.append(_row("buvid3", bundle.buvid3))
    lines.append("")  # 末尾空行避免某些解析器报错

    fd, path = tempfile.mkstemp(prefix="fvd_bili_", suffix=".cookies.txt", text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fp:
            fp.write("\n".join(lines))
    except Exception:
        try:
            os.unlink(path)
        except OSError:
            pass
        raise
    return path


def safe_unlink(path: str | None) -> None:
    if not path:
        return
    try:
        os.unlink(path)
    except OSError:
        pass


def build_subtitle_request_headers(url: str, bundle: BilibiliCookieBundle | None = None) -> dict[str, str]:
    """字幕 / API 直链请求时的 HTTP 头。

    - 对 B 站域名拼上 Referer + UA + Cookie；
    - 其他域名只回默认 UA，避免误带 Cookie 给第三方。
    """
    if not is_bilibili_url(url):
        return {"User-Agent": "Mozilla/5.0 (compatible; FreeVideoDownload/1.0)", "Accept": "*/*"}

    bundle = bundle or get_cookie_bundle()
    headers = {
        "User-Agent": BILIBILI_USER_AGENT,
        "Accept": "*/*",
        "Referer": BILIBILI_REFERER,
        "Origin": BILIBILI_REFERER,
    }
    cookie = bundle.cookie_header()
    if cookie:
        headers["Cookie"] = cookie
    return headers
